language: python

matrix:
  include:
    - name: "Python 3.7 on Bionic Linux"
      python: "3.7"
      dist: bionic
    - name: "Python 3.7 on Xenial Linux"
      python: "3.7"
      dist: xenial

install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create --file ml.yml
  - conda activate ml
  - python3 -m pip freeze

script:
  - pytest

notifications:
  email: false
